<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Faker\Factory as Faker;

class RepresentantesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $representantes = [
            // SP - cidade_id: 1
            [
                'cpf' => '90000000001',
                'nome' => 'José Representante 1',
                'data_nascimento' => '1980-01-01',
                'sexo' => 'M',
                'endereco' => 'Rua A, 100',
                'estado' => 'SP',
                'cidade_id' => 1,
                'telefone' => '(11) 91111-1111',
                'email' => 'jose.rep1@exemplo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cpf' => '90000000002',
                'nome' => 'Paula Representante 2',
                'data_nascimento' => '1981-02-02',
                'sexo' => 'F',
                'endereco' => 'Rua B, 200',
                'estado' => 'SP',
                'cidade_id' => 1,
                'telefone' => '(11) 92222-2222',
                'email' => 'paula.rep2@exemplo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cpf' => '90000000003',
                'nome' => 'Carlos Representante 3',
                'data_nascimento' => '1982-03-03',
                'sexo' => 'M',
                'endereco' => 'Rua C, 300',
                'estado' => 'SP',
                'cidade_id' => 1,
                'telefone' => '(11) 93333-3333',
                'email' => 'carlos.rep3@exemplo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // RJ - cidade_id: 2
            [
                'cpf' => '90000000004',
                'nome' => 'Fernanda Representante 1',
                'data_nascimento' => '1983-04-04',
                'sexo' => 'F',
                'endereco' => 'Av. Leste, 400',
                'estado' => 'RJ',
                'cidade_id' => 2,
                'telefone' => '(21) 94444-4444',
                'email' => 'fernanda.rep1@exemplo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cpf' => '90000000005',
                'nome' => 'Rafael Representante 2',
                'data_nascimento' => '1984-05-05',
                'sexo' => 'M',
                'endereco' => 'Av. Oeste, 500',
                'estado' => 'RJ',
                'cidade_id' => 2,
                'telefone' => '(21) 95555-5555',
                'email' => 'rafael.rep2@exemplo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cpf' => '90000000006',
                'nome' => 'Juliana Representante 3',
                'data_nascimento' => '1985-06-06',
                'sexo' => 'F',
                'endereco' => 'Av. Norte, 600',
                'estado' => 'RJ',
                'cidade_id' => 2,
                'telefone' => '(21) 96666-6666',
                'email' => 'juliana.rep3@exemplo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // MG - cidade_id: 3
            [
                'cpf' => '90000000007',
                'nome' => 'Luiz Representante 1',
                'data_nascimento' => '1986-07-07',
                'sexo' => 'M',
                'endereco' => 'Praça Alfa, 700',
                'estado' => 'MG',
                'cidade_id' => 3,
                'telefone' => '(31) 97777-7777',
                'email' => 'luiz.rep1@exemplo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cpf' => '90000000008',
                'nome' => 'Bianca Representante 2',
                'data_nascimento' => '1987-08-08',
                'sexo' => 'F',
                'endereco' => 'Praça Beta, 800',
                'estado' => 'MG',
                'cidade_id' => 3,
                'telefone' => '(31) 98888-8888',
                'email' => 'bianca.rep2@exemplo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cpf' => '90000000009',
                'nome' => 'Eduardo Representante 3',
                'data_nascimento' => '1988-09-09',
                'sexo' => 'M',
                'endereco' => 'Praça Gama, 900',
                'estado' => 'MG',
                'cidade_id' => 3,
                'telefone' => '(31) 99999-9999',
                'email' => 'eduardo.rep3@exemplo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // BA - cidade_id: 4
            [
                'cpf' => '90000000010',
                'nome' => 'Tatiane Representante 1',
                'data_nascimento' => '1989-10-10',
                'sexo' => 'F',
                'endereco' => 'Rua Delta, 1000',
                'estado' => 'BA',
                'cidade_id' => 4,
                'telefone' => '(71) 91000-0001',
                'email' => 'tatiane.rep1@exemplo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cpf' => '90000000011',
                'nome' => 'Diego Representante 2',
                'data_nascimento' => '1990-11-11',
                'sexo' => 'M',
                'endereco' => 'Rua Epsilon, 1100',
                'estado' => 'BA',
                'cidade_id' => 4,
                'telefone' => '(71) 92000-0002',
                'email' => 'diego.rep2@exemplo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cpf' => '90000000012',
                'nome' => 'Isabela Representante 3',
                'data_nascimento' => '1991-12-12',
                'sexo' => 'F',
                'endereco' => 'Rua Zeta, 1200',
                'estado' => 'BA',
                'cidade_id' => 4,
                'telefone' => '(71) 93000-0003',
                'email' => 'isabela.rep3@exemplo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // CE - cidade_id: 5
            [
                'cpf' => '90000000013',
                'nome' => 'Márcio Representante 1',
                'data_nascimento' => '1980-01-13',
                'sexo' => 'M',
                'endereco' => 'Rua Sol Nascente, 1300',
                'estado' => 'CE',
                'cidade_id' => 5,
                'telefone' => '(85) 91111-1113',
                'email' => 'marcio.rep1@exemplo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cpf' => '90000000014',
                'nome' => 'Débora Representante 2',
                'data_nascimento' => '1981-02-14',
                'sexo' => 'F',
                'endereco' => 'Rua do Mar, 1400',
                'estado' => 'CE',
                'cidade_id' => 5,
                'telefone' => '(85) 92222-2214',
                'email' => 'debora.rep2@exemplo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cpf' => '90000000015',
                'nome' => 'Otávio Representante 3',
                'data_nascimento' => '1982-03-15',
                'sexo' => 'M',
                'endereco' => 'Av. Ceará, 1500',
                'estado' => 'CE',
                'cidade_id' => 5,
                'telefone' => '(85) 93333-3315',
                'email' => 'otavio.rep3@exemplo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // PR - cidade_id: 6
            [
                'cpf' => '90000000016',
                'nome' => 'Elaine Representante 1',
                'data_nascimento' => '1983-04-16',
                'sexo' => 'F',
                'endereco' => 'Rua Paraná, 1600',
                'estado' => 'PR',
                'cidade_id' => 6,
                'telefone' => '(41) 94444-4416',
                'email' => 'elaine.rep1@exemplo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cpf' => '90000000017',
                'nome' => 'Rodrigo Representante 2',
                'data_nascimento' => '1984-05-17',
                'sexo' => 'M',
                'endereco' => 'Av. Curitiba, 1700',
                'estado' => 'PR',
                'cidade_id' => 6,
                'telefone' => '(41) 95555-5517',
                'email' => 'rodrigo.rep2@exemplo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cpf' => '90000000018',
                'nome' => 'Renata Representante 3',
                'data_nascimento' => '1985-06-18',
                'sexo' => 'F',
                'endereco' => 'Rua das Araucárias, 1800',
                'estado' => 'PR',
                'cidade_id' => 6,
                'telefone' => '(41) 96666-6618',
                'email' => 'renata.rep3@exemplo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // AM - cidade_id: 7
            [
                'cpf' => '90000000019',
                'nome' => 'Bruno Representante 1',
                'data_nascimento' => '1986-07-19',
                'sexo' => 'M',
                'endereco' => 'Av. Amazonas, 1900',
                'estado' => 'AM',
                'cidade_id' => 7,
                'telefone' => '(92) 97777-7719',
                'email' => 'bruno.rep1@exemplo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cpf' => '90000000020',
                'nome' => 'Simone Representante 2',
                'data_nascimento' => '1987-08-20',
                'sexo' => 'F',
                'endereco' => 'Rua Manaus, 2000',
                'estado' => 'AM',
                'cidade_id' => 7,
                'telefone' => '(92) 98888-8820',
                'email' => 'simone.rep2@exemplo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cpf' => '90000000021',
                'nome' => 'Hugo Representante 3',
                'data_nascimento' => '1988-09-21',
                'sexo' => 'M',
                'endereco' => 'Travessa Rio Negro, 2100',
                'estado' => 'AM',
                'cidade_id' => 7,
                'telefone' => '(92) 99999-9921',
                'email' => 'hugo.rep3@exemplo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // PE - cidade_id: 8
            [
                'cpf' => '90000000022',
                'nome' => 'Tatiana Representante 1',
                'data_nascimento' => '1989-10-22',
                'sexo' => 'F',
                'endereco' => 'Av. Recife, 2200',
                'estado' => 'PE',
                'cidade_id' => 8,
                'telefone' => '(81) 91000-0022',
                'email' => 'tatiana.rep1@exemplo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cpf' => '90000000023',
                'nome' => 'Alex Representante 2',
                'data_nascimento' => '1990-11-23',
                'sexo' => 'M',
                'endereco' => 'Rua Boa Viagem, 2300',
                'estado' => 'PE',
                'cidade_id' => 8,
                'telefone' => '(81) 92000-0023',
                'email' => 'alex.rep2@exemplo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cpf' => '90000000024',
                'nome' => 'Camila Representante 3',
                'data_nascimento' => '1991-12-24',
                'sexo' => 'F',
                'endereco' => 'Rua Olinda, 2400',
                'estado' => 'PE',
                'cidade_id' => 8,
                'telefone' => '(81) 93000-0024',
                'email' => 'camila.rep3@exemplo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // RS - cidade_id: 9
            [
                'cpf' => '90000000025',
                'nome' => 'Vinícius Representante 1',
                'data_nascimento' => '1980-01-25',
                'sexo' => 'M',
                'endereco' => 'Av. Porto Alegre, 2500',
                'estado' => 'RS',
                'cidade_id' => 9,
                'telefone' => '(51) 91111-1125',
                'email' => 'vinicius.rep1@exemplo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cpf' => '90000000026',
                'nome' => 'Marina Representante 2',
                'data_nascimento' => '1981-02-26',
                'sexo' => 'F',
                'endereco' => 'Rua dos Andradas, 2600',
                'estado' => 'RS',
                'cidade_id' => 9,
                'telefone' => '(51) 92222-2226',
                'email' => 'marina.rep2@exemplo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cpf' => '90000000027',
                'nome' => 'Thiago Representante 3',
                'data_nascimento' => '1982-03-27',
                'sexo' => 'M',
                'endereco' => 'Rua Gramado, 2700',
                'estado' => 'RS',
                'cidade_id' => 9,
                'telefone' => '(51) 93333-3327',
                'email' => 'thiago.rep3@exemplo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('representantes')->insert($representantes);
    }
}